### ISSUE TITLE
我们这边的outlook客户端一直报错，我想用最新版的

### ISSUE THREAD

**Issue by yuenwah** [yasoonOfficial/com.yasoon.jira#1]
![image](https://user-images.githubusercontent.com/34834139/56333492-f5658200-61c6-11e9-9906-bd15f662ea39.png)
就一直是这样

**Comment by tobiasviehweger** [comment]
Hi @yuenwah,

please raise your issue in our normal issue tracker:
https://yasoon.atlassian.net/servicedesk/customer/portal/3

Thanks
Tobias
